
@storeId = 1234567890
@userSrl = 2

### 권한 부여
POST http://localhost:8080/api/v1/stores/{{storeId}}/assignments?managerId={{userSrl}}
X-Admin-Role: ADMIN


### 권한 회수
DELETE http://localhost:8080/api/v1/stores/{{storeId}}/assignments?userSrl={{userSrl}}
X-Admin-Role: ADMIN

### 권한 조회
GET http://localhost:8080/api/v1/stores/{{storeId}}/permissions/me?userSrl={{userSrl}}
